include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-custom-image.yml'

stages:
  - package
  - test-package
  - deploy

variables:
  PROJECT_PARENT_NAME: index

.deploy:
  variables:
    STACK: ${PROJECT_PARENT_NAME}
    SERVICES_TO_CHECK: ${PROJECT_PARENT_NAME}_${CI_PROJECT_NAME}
    STATUS_CHECK_DELAY: 60
  environment:
    url: https://${PROJECT_PARENT_NAME}.${PUBLIC_HOSTNAME}

.deploy-compose-file:
  variables: &deploy-compose-file-variables
    COMPOSE_FILE: docker-compose.yml

.deploy-development:
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SSH_PORT: ${PRO_SSH_PORT}
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
    DD_PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
    <<: *deploy-compose-file-variables

.deploy-production:
  variables:
    <<: *deploy-compose-file-variables
