include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment-custom-image.yml'

stages:
  - pre-package
  - package
  - post-package
  - deploy

variables:
  COMPOSE_NAME: docker-compose.yml

.docker-build:
  variables:
    COMPOSE_FILE_NAME: ${COMPOSE_NAME}

.deploy:
  variables:
    STACK: index
    STATUS_CHECK_DELAY: 60

.deploy-compose-file:
  variables: &deploy-compose-file-variables
    COMPOSE_FILE: ${COMPOSE_NAME}

.deploy-development:
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SSH_PORT: ${PRO_SSH_PORT}
    PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
    DD_PUBLIC_HOSTNAME: ${PRO_PUBLIC_HOSTNAME}
    <<: *deploy-compose-file-variables

.deploy-production:
  variables:
    <<: *deploy-compose-file-variables
